# Generated by Django 5.1.2 on 2024-11-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("nom", models.CharField(max_length=255)),
                ("prenom_1", models.CharField(blank=True, max_length=255)),
                ("prenom_2", models.CharField(blank=True, max_length=255)),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Code Postal"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
